include:
  - board: nice_nano
    shield: dactyl_manuform_6x6_left
    artifact-name: dactyl-manuform-6x6-left
  - board: nice_nano
    shield: settings_reset
    artifact-name: adafruit-nice-nano-settings-reset
