include:
  - board: promicro_nrf52840/nrf52840/uf2
    shield: dactyl_manuform_6x6_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: dactyl-manuform-6x6-left
  - board: promicro_nrf52840/nrf52840/uf2
    shield: dactyl_manuform_6x6_right
    artifact-name: dactyl-manuform-6x6-right
  - board: promicro_nrf52840/nrf52840/uf2
    shield: settings_reset
    artifact-name: adafruit-nice-nano-settings-reset
